Суслова Даша, БКЛ141, 02 задачи 1-3 и 5
mkuznets/hse-ling-algorithms pull request #1
Opened 2017-01-30 19:06 UTC by dariasuslova

2017-01-30 20:16 UTC, mkuznets requested changes
Ожидаю исправлений по откомментированным местам вплоть до дедлайна. Новый пулл-реквест делать не нужно, достаточно просто добавить новые коммиты в ту же ветку и сделать push.

2017-01-30 20:16 UTC, mkuznets commented on students/DariaSuslova/valid_parentheses/valid_parentheses_listok2.py
> +    def isValid(self, s):
А что будет, если строка состоит из одних лишь открывающих скобок?

2017-01-30 20:16 UTC, mkuznets commented on students/DariaSuslova/reverse_linked_list/reverse_linked_list_listok2.py
> +    def reverseList(self, head):
LGTM

2017-01-30 20:16 UTC, mkuznets commented on students/DariaSuslova/findMin/findMin_listok2.py
> +        nums.sort()
Время работы требуемое по условию задачи — `O(log(n))`, а одна только сортировка требует `O(nlog(n))`

2017-01-30 20:16 UTC, mkuznets commented on students/DariaSuslova/move_zeroes/move_zeroes_listok2.py
> +    def moveZeroes(self, nums):
Идея верная, но из-за опечатки работает некорректно.

2017-02-04 20:40 UTC, mkuznets approved these changes

2017-02-04 20:47 UTC, mkuznets commented on students/DariaSuslova/linked_list_cycle/linked_list_cycle_listok_2.py
> +    def hasCycle(self, head):
Не работает с пустым списком

2017-02-04 20:50 UTC, mkuznets commented
Пока зачтены:
* findMin
* move_zeroes
* reverse_linked_list

Не зачтены:
* linked_list_cycle
* valid_parentheses

2017-02-04 21:12 UTC, dariasuslova commented on students/DariaSuslova/linked_list_cycle/linked_list_cycle_listok_2.py
> +    def hasCycle(self, head):
странно, мне казалось, что функция в этом случае вроде как False выдает

2017-02-04 21:15 UTC, mkuznets commented on students/DariaSuslova/linked_list_cycle/linked_list_cycle_listok_2.py
> +    def hasCycle(self, head):
4-я строка

2017-02-04 23:16 UTC, merged